/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_03_66/packages/ti/mcu/msp430/csl2/comparator/Comparator_E_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/comp_e.h>
#include "_Grace.h"

/* USER CODE START (section: Comparator_E_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: Comparator_E_init_c_prologue) */

/*
 *  ======== Comparator_E_graceInit ========
 *  Initialize Config for the MSP430FR5xx Comparator_E
 */
void Comparator_E_graceInit(void)
{

    /* USER CODE START (section: Comparator_E_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: Comparator_E_graceInit_prologue) */


    /* USER CODE START (section: Comparator_E_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: Comparator_E_graceInit_epilogue) */

}
