/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_03_66/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>
#include "_Grace.h"

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
#include <msp430.h>
#include "_Grace.h"
#include <driverlib/MSP430FR5xx_6xx/dma.h>
#include <driverlib/MSP430FR5xx_6xx\timer_a.h>
//////////////////////////////////////////////////////////////////////////
// Hardware                                        ///////////////////////
// MSP430FR5949IRHA Hardware  -- Port definitions  ///////////////////////
//////////////////////////////////////////////////////////////////////////

     // MASTER definitions  (some are used in the SLAVEs as well)
             // Janus Phone board power settings (MASTER)
     #define PHNMON_STATUS           (P2IN & BIT7)           // Test indicator of phone board status (the meaning of blinking is different for different Janus boards)
     #define PHNMON_LED_OFF          P4OUT &= ~BIT0          // Turn off phone board status LED
     #define PHNMON_LED_ON           P4OUT |= BIT0           // Turn on phone board status LED
     #define PHONE_IS_ON             (P2IN & BIT3)           // The phone is on

             // UART Settings for connection to Janus Phone board (MASTER)
             // The Phone board uses UCA1
     #define PHONE_RX_BUFF           UCA1RXBUF               // The receive buffer for the Master UART
     #define PHONE_TX_BUFF           UCA1TXBUF               // The transmit buffer for the Master UART

             // UART settings for Coax connection for smart sensors (MASTER and SLAVE)
             // The sensor communications uses UCA0
     #define COAX_TX_BUFF            UCA0TXBUF               // The transmit buffer for the COAX UART
     #define COAX_RX_BUFF            UCA0RXBUF               // The receive buffer for the COAX UART

                     //Other hardware ports used (MASTER)
     #define LED_ON          P4OUT |= BIT0               // Test LED (can be disabled in runtime version)
     #define LED_OFF         P4OUT &= ~BIT0
     #define RED_LED_ON      P4OUT |= BIT1               // Power indicator
     #define RED_LED_OFF     P4OUT &= ~BIT1
     #define GREEN_LED_ON    P4OUT |= BIT0               // Communications status
     #define GREEN_LED_OFF   P4OUT &= ~BIT0


     #define END_LOW_POWER_MODE    __bic_SR_register_on_exit(LPM0_bits)

            // ADXL UART Settings for connection to Janus Phone board (MASTER)
            // The ADXL sensor uses UCA1 in SPI mode
     #define ADXL_RX_BUFF           UCA1RXBUF               // The receive buffer for the Master UART
     #define ADXL_TX_BUFF           UCA1TXBUF               // The transmit buffer for the Master UART


// external variables
    extern volatile unsigned char waiting;              // a flag used with the wait() timer.
    extern volatile unsigned char interval_count;       // Clock timing.  Each interval (1/8 sec) creates an interrupt
    extern volatile unsigned char interval_limit;       // The intervals are counted and counting restarts when the limit is reached.
    extern volatile unsigned char intervals_on;         // whether to wake up every 1/8 second
    extern const unsigned char not_slave;               // 0 is a slave, 1 is a master.
    extern volatile unsigned char registering;
    extern volatile unsigned int coax_tx_buff_len;          // The length of the buffer for transmitting to UCA0
    extern volatile unsigned char *coax_tx_buff_ptr;        // The pointer to the transmit buffer.
    extern volatile unsigned char waiting_for_coax_data;    // a flag reset by the receive interrupt

    volatile unsigned char coax_char_received;              // used to empty the coax RX buffer

#define YES 1
#define NO 0
     /* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}

/*
 *  ======== Timer0_A3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_A0_VECTOR
__interrupt void TIMER0_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_A0_ISR_HOOK) */

        END_LOW_POWER_MODE;

    /* USER CODE END (section: TIMER0_A0_ISR_HOOK) */
}


/*
 *  ======== Timer0_B7 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_B0_VECTOR
__interrupt void TIMER0_B0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_B0_ISR_HOOK) */

    // This timer will keep the clock for timing events
    // The interrupts happen every 1/8th of a second continuously
    // a unit can reset its interval counter to synch up to command

    if (++interval_count == interval_limit) interval_count = 0; //count up to the interval limit and repeat
    if (not_slave && PHONE_IS_ON)    // the master monitors the phone with the LED when it is on
    {   if (PHNMON_STATUS) PHNMON_LED_ON;
        else PHNMON_LED_OFF;
    }
    if (intervals_on)
        END_LOW_POWER_MODE;
        // only wake up if the intervals_on flag is set

    /* USER CODE END (section: TIMER0_B0_ISR_HOOK) */
}


/*
 *  ======== Timer2_A2 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER2_A0_VECTOR
__interrupt void TIMER2_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER2_A0_ISR_HOOK) */
    // This timer is used to sleep or time a specified number of milliseconds
    // It is started and stopped as needed

    if (waiting)        // if asleep, wake up
    {   waiting = NO;   // we are done waiting
        END_LOW_POWER_MODE;
    }

    /* USER CODE END (section: TIMER2_A0_ISR_HOOK) */
}



/*
 *  ======== eUSCI_A0 Interrupt Service Routine ========
 */
#pragma vector=USCI_A0_VECTOR
__interrupt void USCI_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI_A0_ISR_HOOK) */

    switch(__even_in_range(UCA0IV,UCTXCPTIFG))
    {
       case USCI_UART_UCTXCPTIFG: //Finished xmitting
           if(!(coax_tx_buff_len || (UCA0STATW&UCBUSY)))
           {
               UCA0IE &= ~UCTXCPTIFG; //We're done
               END_LOW_POWER_MODE;    //wakeup
           }
           break;

       case USCI_UART_UCSTTIFG:     //Used for avoing collisions with registerring sensors
           if (registering)
           {   registering = NO;
               END_LOW_POWER_MODE;
           }
           break;

       case USCI_UART_UCTXIFG:
           if(! coax_tx_buff_len)
           {
               UCA0IE &= ~UCTXIE;   //No more chars, so, disable TXIFG
               break;
           }
           UCA0TXBUF= *coax_tx_buff_ptr++;
           coax_tx_buff_len--;
           break;

       case USCI_UART_UCRXIFG:                  //If we are here, then a byte has been received
           coax_char_received = COAX_RX_BUFF;   //store byte to reset interrupt flag
           if (waiting_for_coax_data)           // if we were waiting for data
           {   waiting_for_coax_data = NO;      // we're not now
               END_LOW_POWER_MODE;              // so wake-up
           }
           break;

       case 0: //Spurious?
           break;
    }
    /* USER CODE END (section: USCI_A0_ISR_HOOK) */
}

/*
 *  ======== eUSCI_A1 Interrupt Service Routine ========
 */
#pragma vector=USCI_A1_VECTOR
__interrupt void USCI_A1_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI_A1_ISR_HOOK) */

    switch(__even_in_range(UCA1IV,UCTXCPTIFG))
    {
       case USCI_UART_UCTXCPTIFG: //Finished xmitting

               UCA1IE &= ~UCTXCPTIFG; //We're done
               END_LOW_POWER_MODE;    //wakeup

           break;

       case USCI_UART_UCSTTIFG:

           break;

       case USCI_UART_UCTXIFG:

               UCA0IE &= ~UCTXIE;   //No more chars, so, disable TXIFG
               END_LOW_POWER_MODE;    //wakeup
           break;

       case USCI_UART_UCRXIFG:                  //If we are here, then a byte has been received
           coax_char_received = COAX_RX_BUFF;   //store byte to reset interrupt flag

           END_LOW_POWER_MODE;              // so wake-up

           break;

       case 0: //Spurious?
           break;
    }
    /* USER CODE END (section: USCI_A1_ISR_HOOK) */
}
