/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_03_66/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>
#include "_Grace.h"

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
#include <msp430.h>
#include "_Grace.h"
#include <driverlib/MSP430FR5xx_6xx/dma.h>
#include <driverlib/MSP430FR5xx_6xx\timer_a.h>
//////////////////////////////////////////////////////////////////////////
// Hardware                          /////////////////////////////////////
// MSP430FR5969 -- Port definitions  /////////////////////////////////////
//////////////////////////////////////////////////////////////////////////



// MSP430FR5949IRHA Hardware  -- Port definitions  ///////////////////////////////////////////////////////////////

   // MSP430FR5949IRHA Hardware  -- Port definitions  ///////////////////////////////////////////////////////////////

     // MASTER definitions  (some are used in the SLAVEs as well)
             // Janus Phone board power settings (MASTER)
     #define PHONE_POWER_ENABLE      P3OUT |= BIT7           // Turn on the 5 V power supply
     #define PHONE_POWER_DISABLE     P3OUT &= ~ BIT7         // Turn off the 5 V power supply
     #define PHONE_ON_OFF_REQUEST    P2OUT &= ~ BIT4         // Turn the phone on or off (must be held low for a while)
     #define PHONE_ON_OFF_HIZ        P2OUT |= BIT4           // When not turning the phone on or off it stays hi
     #define PHONE_RESET_REQUEST     P3OUT &= ~ BIT1         // Reset the phone by holding this bit low
     #define PHONE_RESET_HIZ         P3OUT |= BIT1           // When not resetting, it stays hi
     #define PHONE_IS_ON             (P2IN & BIT3)           // The phone is on
     #define PHONE_IS_OFF            (!(P2IN & BIT3))        // The phone is off
     #define PHNMON_STATUS           (P2IN & BIT7)           // Test indicator of phone board status (the meaning of blinking is different for different Janus boards)
     #define PHNMON_LED_OFF          P4OUT &= ~BIT0          // Turn off phone board status LED
     #define PHNMON_LED_ON           P4OUT |= BIT0           // Turn on phone board status LED

             // Sensor Power Supply (MASTER)
     #define COAX_POWER_ENABLE       P3OUT |= BIT5           // Start up the sensors
     #define COAX_POWER_DISABLE      P3OUT &= ~BIT5          // Turn off the sensors

             // Auxiliary Power Supply (MASTER)
     #define AUX_POWER_ENABLE        P3OUT |= BIT6           // Turn on the aux power
     #define AUX_POWER_DISABLE       P3OUT &= ~BIT5          // Turn off the aux power

             // UART Settings for connection to Janus Phone board (MASTER)
             // The Phone board uses UCA1
     #define PHONE_BUSY              (UCA1STATW & UCBUSY)    // The eUSCI module is transmitting or receiving
     #define PHONE_READY             (!(UCA1STATW & UCBUSY)) // The eUSCI module is not transmitting or receiving
     #define PHONE_RX_BUFF           UCA1RXBUF               // The receive buffer for the Master UART
     #define PHONE_TX_BUFF           UCA1TXBUF               // The transmit buffer for the Master UART
     #define PHONE_TX_READY          (UCA1IFG & UCTXIFG)     // Checks the TX buffer interrupt flag is set
     #define PHONE_TX_NOT_READY      (!(UCA1IFG & UCTXIFG))  // checks if anything is in the TX buffer
     #define PHONE_TX_DONE           (UCA1IFG & UCTXCPTIFG)  // looks to see if the byte has been sent
     #define PHONE_RX_ENABLE         UCA1IE |= UCRXIE        // enable receive buffer interrupts
     #define PHONE_RX_DISABLE        UCA1IE &= ~UCRXIE       // disable receive buffer interrupts
     #define PHONE_RX_BUFF_EMPTY     (!(UCA1RXBUF))
     #define PHONE_TX_ENABLE         UCA1IE |= UCTXIE        // enable transmit buffer empty interrupts
     #define PHONE_TX_DISABLE        UCA1IE &= ~UCTXIE       // disable transmit buffer empty interrupts
     #define PHONE_TX_DONE_ENABLE    UCA1IE |= UCTXCPTIE     // enable transmit complete interrupts
     #define PHONE_TX_DONE_DISABLE   UCA1IE &= ~UCTXCPTIE    // disable transmit complete interrupts
     #define PHONE_UART_RESET        UCA1CTL1 |= UCSWRST     // Put Master's eUSCI in reset
     #define PHONE_UART_ENABLE       UCA1CTL1 &= ~UCSWRST    // release Master's eUSCI from reset
     #define PHONE_INTERRUPT_DISABLE UCA1IE = 0              // disable all UART interrupts
     #define PHONE_USES_SMCLK        UCA1CTL1 |= UCSSEL__SMCLK //Set the UART timing based on the SMCLK



             // UART settings for Coax connection for smart sensors (MASTER and SLAVE)
             // The sensor communications uses UCA0

     #define COAX_TX_BUFF            UCA0TXBUF               // The transmit buffer for the Master UART
     #define COAX_TX_READY           (UCA0IFG & UCTXIFG)     // Checks the TX buffer interrupt flag is set
     #define COAX_TX_NOT_READY       (!(UCA0IFG & UCTXIFG))  // checks if anything is in the TX buffer
     #define COAX_TX_DONE            (UCA0IFG & UCTXCPTIFG)   // looks to see if the byte has been sent
     #define COAX_TX_NOT_DONE        (!(UCA0IFG & UCTXCPTIFG))
     #define COAX_TX_ENABLE          UCA0IE |= UCTXIE        // enable transmit buffer empty interrupts
     #define COAX_TX_DISABLE         UCA0IE &= ~UCTXIE       // disable transmit buffer empty interrupts
     #define COAX_TX_DONE_ENABLE     UCA0IE |= UCTXCPTIE     // enable transmit complete interrupts
     #define COAX_TX_DONE_DISABLE    UCA0IE &= ~UCTXCPTIE    // disable transmit complete interrupts
     #define COAX_RX_BUFF            UCA0RXBUF               // The receive buffer for the Master UART
     #define COAX_RX_BUFF_EMPTY      (!(UCA0IFG & UCRXIFG))  // monitor UART rx buffer
     #define COAX_RX_ENABLE          UCA0IE |= UCRXIE        // enable receive buffer interrupts
     #define COAX_RX_DISABLE         UCA0IE &= ~UCRXIE       // disable receive buffer interrupts
     #define COAX_BUSY               (UCA0STATW & UCBUSY)    // The eUSCI module is transmitting or receiving
     #define COAX_READY              (!(UCA0STATW & UCBUSY)) // The eUSCI module is not transmitting or receiving
     #define COAX_UART_RESET         UCA0CTL1 |= UCSWRST     // Put Master's eUSCI in reset
     #define COAX_UART_ENABLE        UCA0CTL1 &= ~UCSWRST    // release Master's eUSCI from reset
     #define COAX_INTERRUPT_DISABLE  UCA0IE = 0              // disable all UART interrupts
     #define COAX_USES_SMCLK         UCA0CTL1 |= UCSSEL__SMCLK //Set the UART timing based on the SMCLK
     #define COAX_DMA_ENABLE         DMA_enableInterrupt     // Set the DMA receive source to the UART buffer
     #define COAX_DMA_DISABLE        DMA_disableInterrupt    // Set the DMA receive destination to the beginning of the data buffer
     #define COAX_DMA_RX_DESTINATION0 DMA_setDstAddress(DMA_CHANNEL_0, (uint32_t) data_received, DMA_DIRECTION_UNCHANGED)
     #define COAX_DMA_RX_SOURCE0      DMA_setSrcAddress(DMA_CHANNEL_0, (uint32_t) &UCA0RXBUF, DMA_DIRECTION_UNCHANGED)
     #define COAX_DMA_RX_DESTINATION1 DMA_setDstAddress(DMA_CHANNEL_1, (uint32_t) data_received+1, DMA_DIRECTION_INCREMENT)
     #define COAX_DMA_RX_SOURCE1      DMA_setSrcAddress(DMA_CHANNEL_1, (uint32_t) &UCA0RXBUF, DMA_DIRECTION_UNCHANGED)
     #define DMA_SHORT_SIZE          0x0B                    // The length of a short coax message

                     //Other hardware ports used (MASTER)
     #define LED_ON          P4OUT |= BIT0               // Test LED (can be disabled in runtime version)
     #define LED_OFF         P4OUT &= ~BIT0
     #define RED_LED_ON      P4OUT |= BIT1               // Power indicator
     #define RED_LED_OFF     P4OUT &= ~BIT1
     #define GREEN_LED_ON    P4OUT |= BIT0               // Communications status
     #define GREEN_LED_OFF   P4OUT &= ~BIT0


     #define END_LOW_POWER_MODE    __bic_SR_register_on_exit(LPM0_bits)

                     // Timer controls
     #define MSEC_TIMER          TA2CTL
     #define START_MSEC_TIMER    MSEC_TIMER |= 0x0010    // turn on bit 4  to start the timer in up mode
     #define STOP_MSEC_TIMER     MSEC_TIMER &= 0xFFBF    // turn off bits 4 and 5 to stop the timer

     #define NO 0

     #define SMCLK_OFF       P3SEL1 &= ~BIT4                 // turn off the SMCLK output on P3.4
     #define SMCLK_ON        P3SEL1 |= BIT4                  // turn on the SMCLK output on P3.4


     // SLAVE definitions  (these settings are unique to the SLAVEs)
             // ADXL Accelerometer power (SLAVE)
     #define ADXL_POWER_ON     P2OUT |= BIT7               // Pin 2.2 powers the sensor
     #define ADXL_POWER_OFF    P2OUT &= ~BIT7              // All ADXL pins must be zeroed to reset the sensor

             // ADXL UART Settings for connection to Janus Phone board (MASTER)
             // The ADXL sensor uses UCA1 in SPI mode
     #define ADXL_UART_ON           EUSCI_A_UART_enable(EUSCI_A1_BASE)
     #define ADXL_UART_OFF          EUSCI_A_UART_disable(EUSCI_A1_BASE)
     #define ADXL_UART_RESET        UCA1CTL1 |= UCSWRST     // Put Master's eUSCI in reset
     #define ADXL_UART_ENABLE       UCA1CTL1 &= ~UCSWRST    // release Master's eUSCI from reset
     #define ADXL_BUSY              (UCA1STATW & UCBUSY)    // The eUSCI module is transmitting or receiving
     #define ADXL_READY             (!(UCA1STATW & UCBUSY)) // The eUSCI module is not transmitting or receiving
     #define ADXL_RX_BUFF           UCA1RXBUF               // The receive buffer for the Master UART
     #define ADXL_TX_BUFF           UCA1TXBUF               // The transmit buffer for the Master UART
     #define ADXL_TX_READY          (UCA1IFG & UCTXIFG)     // Checks the TX buffer interrupt flag is set
     #define ADXL_TX_NOT_READY      (!(UCA1IFG & UCTXIFG))  // checks if anything is in the TX buffer
     #define ADXL_TX_DONE           (UCA1IFG & UCTXCPTIFG)  // looks to see if the byte has been sent
     #define ADXL_RX_ENABLE         UCA1IE |= UCRXIE        // enable receive buffer interrupts
     #define ADXL_RX_DISABLE        UCA1IE &= ~UCRXIE       // disable receive buffer interrupts
     #define ADXL_RX_BUFF_EMPTY     (!(UCA1RXBUF))
     #define ADXL_RX_NOT_READY      (!(UCA1IFG & UCRXIFG))  // But location to monitor while receiving data is in process
     #define ADXL_TX_ENABLE         UCA1IE |= UCTXIE        // enable transmit buffer empty interrupts
     #define ADXL_TX_DISABLE        UCA1IE &= ~UCTXIE       // disable transmit buffer empty interrupts
     #define ADXL_TX_DONE_ENABLE    UCA1IE |= UCTXCPTIE     // enable transmit complete interrupts
     #define ADXL_TX_DONE_DISABLE   UCA1IE &= ~UCTXCPTIE    // disable transmit complete interrupts
     #define ADXL_INTERRUPT_DISABLE UCA1IE = 0              // disable all UART interrupts
     #define ADXL_USES_SMCLK        UCA1CTL1 |= UCSSEL__SMCLK //Set the UART timing based on the SMCLK


#define CLOCKSPEED 0x08                         // Set the clock speed (4 MHz)
#define ONE_MHz         0x0000
#define FOUR_MHz        0x0006
#define EIGHT_MHz       0x000C


// Logic
#define YES 1
#define NO 0
#define TRUE 1
#define FALSE 0


// Error codes
#define NO_ERROR            0x00    // everything is good
#define ERROR               0x01    // general error, unspecified error, program error, etc...
#define TIMEOUT_ERROR       0x02    // Timeout counter ranout before response received
#define RX_BUFFER_OVERFLOW  0x03    // Too many chars received

// ASCII codes
#define ASCII_CR    13  // ASCII Carriage Return
#define ASCII_LF    10  // ASCII Line Feed



// external variables
    extern volatile int secCount;
    extern volatile unsigned char not_ready, receiveData, in_conversation, sec_interrupt, not_sleeping, waiting,
                sensor_ready, tamper_count, transmission_done, pause, waiting_for_coax_data, message_in_progress,
                sending_msg, receiving_msg, phone_buffer_full, coax_buffer_full;
    extern volatile unsigned char id_bank, id_number, caller_bank, caller_number, command_bank, command_number;
    extern volatile unsigned char bad_transmission, processing_command, coax_quiet;     //status flags for error and ready to process
    extern volatile unsigned int bytecount;             // counts the number of bytes in the current received command
    extern volatile unsigned long received_datalength;
    extern volatile unsigned long long command_checksum, received_checksum; // keep a checksum to look for conversation errors
    extern volatile unsigned char *data_ptr;
    extern volatile unsigned char data_buffer;           // pointer to the buffer
    extern volatile unsigned char *message_ptr;
    extern volatile unsigned char transmit_byte, last_transmit_byte;       // pointer to the message we are sending, and the byte being sent
    extern volatile unsigned long message_count, message_length; // count the chars sent in the message up to the message length
    extern volatile unsigned int data_count, data_length;       // count the chars sent in the data up to the data length
    extern volatile unsigned char not_timed_out;                      // timeout flag
    extern const unsigned char not_master;              // 0 is a master, 1 is a slave.  Behaves differently with each unit
    extern const unsigned char not_slave;               // 0 is a slave, 1 is a master.
    extern volatile unsigned char  transmitting, registering;
    extern volatile unsigned int coax_tx_buff_len;          // The length of the buffer for transmitting to UCA0
    extern volatile unsigned char *coax_tx_buff_ptr;        // The pointer to the transmit buffer.
    extern volatile unsigned char coax_char_received;
    extern volatile unsigned char interval_count;       // Clock timing.  Each interval (1/8 sec) creates an interrupt
    extern volatile unsigned char interval_limit;       // The intervals are counted and counting restarts when the limit is reached.
    extern volatile unsigned char wait_until_cycle;     // the interval count we are waiting for
    extern volatile unsigned char intervals_on;

///////////// Rx buffer setup
#define DATA_BUFFER_SIZE    0x200  //The size of the data buffer for receiving data from UART or phone
#define FULL                DATA_BUFFER_SIZE
#define EMPTY               0x00

    extern volatile unsigned char buffer_count; //points to the next offset in the buffer
                                                // also indicates status of buffer 00 = empty, FF = full
    extern unsigned char data_received[DATA_BUFFER_SIZE];   //phone data buffer (incoming data)
    extern volatile unsigned char last_rx;
    extern volatile unsigned char cr_count, message_endcount;
    extern volatile unsigned char id_bank, id_number, caller_bank, caller_number, command_bank, command_number;
    extern volatile unsigned char random_wait;

     /* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}

/*
 *  ======== Timer0_A3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_A0_VECTOR
__interrupt void TIMER0_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_A0_ISR_HOOK) */

        END_LOW_POWER_MODE;

    /* USER CODE END (section: TIMER0_A0_ISR_HOOK) */
}


/*
 *  ======== Timer0_B7 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_B0_VECTOR
__interrupt void TIMER0_B0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_B0_ISR_HOOK) */

    // This timer will keep the clock for timing events
    // The interrupts happen every 1/8th of a second continuously
    // a unit can reset its interval counter to synch up to command

    if (++interval_count == interval_limit) interval_count = 0; //count up to the interval limit and repeat
    if (not_slave && PHONE_IS_ON)    // the master monitors the phone with the LED when it is on
    {   if (PHNMON_STATUS) PHNMON_LED_ON;
        else PHNMON_LED_OFF;
    }
    if (intervals_on)
        END_LOW_POWER_MODE;
        // only wake up if the intervals_on flag is set

    /* USER CODE END (section: TIMER0_B0_ISR_HOOK) */
}


/*
 *  ======== Timer2_A2 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER2_A0_VECTOR
__interrupt void TIMER2_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER2_A0_ISR_HOOK) */
    // This timer is used to sleep or time a specified number of milliseconds
    // It is started and stopped as needed

    if (waiting)        // if asleep, wake up
    {   waiting = NO;   // we are done waiting
        END_LOW_POWER_MODE;
    }

    /* USER CODE END (section: TIMER2_A0_ISR_HOOK) */
}



/*
 *  ======== eUSCI_A0 Interrupt Service Routine ========
 */
#pragma vector=USCI_A0_VECTOR
__interrupt void USCI_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI_A0_ISR_HOOK) */

    switch(__even_in_range(UCA0IV,UCTXCPTIFG))
    {
       case USCI_UART_UCTXCPTIFG: //Finished xmitting
           if(!(coax_tx_buff_len || (UCA0STATW&UCBUSY)))
           {
               UCA0IE &= ~UCTXCPTIFG; //We're done
               transmitting = NO;
               END_LOW_POWER_MODE;    //wakeup
           }
           break;

       case USCI_UART_UCSTTIFG:     //Used for avoing collisions with registerring sensors
           if (registering)
           {   registering = NO;
               END_LOW_POWER_MODE;
           }
           break;

       case USCI_UART_UCTXIFG:
           if(! coax_tx_buff_len)
           {
               UCA0IE &= ~UCTXIE;   //No more chars, so, disable TXIFG
               break;
           }
           UCA0TXBUF= *coax_tx_buff_ptr++;
           coax_tx_buff_len--;
           break;

       case USCI_UART_UCRXIFG:                  //If we are here, then a byte has been received
           coax_char_received = COAX_RX_BUFF;   //store byte to reset interrupt flag
           if (waiting_for_coax_data)           // if we were waiting for data
           {   waiting_for_coax_data = NO;      // we're not now
               END_LOW_POWER_MODE;              // so wake-up
           }
           break;

       case 0: //Spurious?
           break;
    }
    /* USER CODE END (section: USCI_A0_ISR_HOOK) */
}

/*
 *  ======== eUSCI_A1 Interrupt Service Routine ========
 */
#pragma vector=USCI_A1_VECTOR
__interrupt void USCI_A1_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI_A1_ISR_HOOK) */

    switch(__even_in_range(UCA1IV,UCTXCPTIFG))
    {
       case USCI_UART_UCTXCPTIFG: //Finished xmitting

               UCA1IE &= ~UCTXCPTIFG; //We're done
               END_LOW_POWER_MODE;    //wakeup

           break;

       case USCI_UART_UCSTTIFG:

           break;

       case USCI_UART_UCTXIFG:

               UCA0IE &= ~UCTXIE;   //No more chars, so, disable TXIFG
               END_LOW_POWER_MODE;    //wakeup
           break;

       case USCI_UART_UCRXIFG:                  //If we are here, then a byte has been received
           coax_char_received = COAX_RX_BUFF;   //store byte to reset interrupt flag

           END_LOW_POWER_MODE;              // so wake-up

           break;

       case 0: //Spurious?
           break;
    }
    /* USER CODE END (section: USCI_A1_ISR_HOOK) */
}
