/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_03_66/packages/ti/mcu/msp430/csl2/timer/ITimerx_B_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/timer_b.h>
#include "_Grace.h"

/* USER CODE START (section: Timer0_B7_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: Timer0_B7_init_c_prologue) */

/*
 *  ======== Timer0_B7_graceInit ========
 *  Initialize Config for the MSP430 7 Timer 0
 */
void Timer0_B7_graceInit(void)
{
    /* USER CODE START (section: Timer0_B7_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: Timer0_B7_graceInit_prologue) */

    /* Select TimerB counter length */
    TIMER_B_selectCounterLength(TIMER_B0_BASE, TIMER_B_COUNTER_16BIT);

    /* Configure TimerB in up mode */
    TIMER_B_configureUpMode(TIMER_B0_BASE, TIMER_B_CLOCKSOURCE_ACLK, TIMER_B_CLOCKSOURCE_DIVIDER_4,
                           1023, TIMER_B_TBIE_INTERRUPT_DISABLE, TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_B_SKIP_CLEAR);

    /* Start TimerB counter */
    TIMER_B_startCounter(TIMER_B0_BASE, TIMER_B_UP_MODE);

    /* USER CODE START (section: Timer0_B7_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: Timer0_B7_graceInit_epilogue) */
}
